import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
const Header =dynamic(() => import('@/components/common/Header/Header'), { ssr: false })

import Footer from "@/components/common/Footer";
import { StoreProvider } from "./redux/StoreProvider";
import dynamic from "next/dynamic";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MediTrust App",
  description: "Generated by Mohamad Osman Goni",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <StoreProvider>
          <div></div>
       <Header/> 
         {children}
        <Footer/>
        </StoreProvider>
      
        
      </body>
    </html>
  );
}
